### PR TITLE
Receiver notifies sender with reasons for discarding envelopes

### PR DESCRIPTION
**Pull request by dshulyak**
On a sender side we want to know if some messages were discarded. For this
purpose new message type was added - messagesResponse. This message type is versioned,
in order to make it transition easier to new message response, if we will want to extend it in near
future.

The response itself is formed from hash of envelopes received in a single batch, and errors encountered
while envelopes were processed. Each error has a code and description, the reason for adding a code
is to provide some kind of user-friendly error to a client explaining why certain envelopes
were not yet delivered. Description will be simply logged on a sender side.

The followup for this change will be an extention on status-go side that will send particular envelope
errors to a client with signals (e.g. status-react).

### CODE REVIEW

**Comment by dshulyak** [comment]
This change can be reviewed

**Comment by mandrigin** [comment]
@dshulyak when integrating into status-go, I'd really love to separate reaction for confirmations vs. errors. Right now, messages are considered "not sent" if a mailserver doesn't send a confirmation back.

So both modes enable message confirmations for *all peers*.
Both modes always notify status-react about sent errors (with a separate signal) and both should log errors. (But using a separate signal).

But only the "hard" mode should actually send a signal to status-react that message is failed to send.

**Comment by dshulyak** [comment]
@mandrigin can't say that i understood your suggestion, also i see some contradiction in next two statements:

> Both modes always notify status-react about sent errors (with a separate signal) and both should log errors. (But using a separate signal).

> But only the "hard" mode should actually send a signal to status-react that message is failed to send.

I was going to notify status-react every time when envelope was discarded by remote peer because of the time issue (potentially including others). This is completely separate signal. status-react can ignore it if some they want to

**Comment by mandrigin** [comment]
@dshulyak okay, but then it will require to mailserver confirmations to be turned on, right? Or will they be turned on by default?

**Comment by dshulyak** [comment]
> @dshulyak okay, but then it will require to mailserver confirmations to be turned on, right? Or will they be turned on by default?

i think that in current version new signal will be sent in both cases. but if mail confirmation are turned on - then it will be sent only if mail server discarded the envelope, not some random peer. so you would prefer not to send a new signal if mail confirmation are turned off, but always log an error?

**Comment by mandrigin** [comment]
@dshulyak no, I just want to be able to keep status quo, so messages aren't marked as "not send" if the mailserver confirmations are disabled.

**Comment by dshulyak** [comment]
> @dshulyak no, I just want to be able to keep status quo, so messages aren't marked as "not send" if the mailserver confirmations are disabled.

these changes probably won't affect that at all. since this is a new signal and it will be sent only when extended "confirmation" is received. so no confirmation with errors - no signal

**Pull request merged**
