### PR TITLE
Use new Prometheus metrics

### PR DESCRIPTION
**Pull request by jakubgs**
Changes:

* Porting existing Whisper metrics to use the new `prometheus/client_golang` library.
* Adding new metrics based on requirements from https://github.com/status-im/status-go/issues/1642
* Adding `Topic` field to `EnvelopeEvent` struct based on https://github.com/status-im/status-react/issues/9081

I'm not entirely sure if `whisper_envelopes_rejected_total` and `whisper_envelopes_cache_failures_total` should be separate metrics. But since the former relates to envelopes rejected before contents validation and latter to ones rejected based on contents validation.

### CODE REVIEW

**Comment by jakubgs** [comment]
Example metrics:
```
 $ curl -s localhost:9305/metrics | grep -P '^whisper'
whisper_envelopes_cache_failures_total{type="low_pow"} 784
whisper_envelopes_cached_total{cache="clear"} 40
whisper_envelopes_cached_total{cache="hit"} 110
whisper_envelopes_cached_total{cache="miss"} 40
whisper_envelopes_received_total 934
whisper_envelopes_size_bytes_bucket{le="1024"} 38
whisper_envelopes_size_bytes_bucket{le="4096"} 38
whisper_envelopes_size_bytes_bucket{le="16384"} 40
whisper_envelopes_size_bytes_bucket{le="65536"} 40
whisper_envelopes_size_bytes_bucket{le="262144"} 40
whisper_envelopes_size_bytes_bucket{le="1.048576e+06"} 40
whisper_envelopes_size_bytes_bucket{le="4.194304e+06"} 40
whisper_envelopes_size_bytes_bucket{le="1.6777216e+07"} 40
whisper_envelopes_size_bytes_bucket{le="6.7108864e+07"} 40
whisper_envelopes_size_bytes_bucket{le="2.68435456e+08"} 40
whisper_envelopes_size_bytes_bucket{le="+Inf"} 40
whisper_envelopes_size_bytes_sum 29226
whisper_envelopes_size_bytes_count 40
whisper_rate_limits_processed_total 0
```

**Comment by adambabik** [comment]
```
whisper_envelopes_size_bytes_bucket{le="1024"} 38
whisper_envelopes_size_bytes_bucket{le="4096"} 38
whisper_envelopes_size_bytes_bucket{le="16384"} 40
```
we could expand it with `256` and `512`.

LGTM otherwise!

**Review by adambabik — COMMENTED** [review]
Unit tests fail.

**Comment by jakubgs** [comment]
@adambabik unit tests fixed.

**Review by adambabik — APPROVED** [review]

**Pull request merged**
